config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'angular#index'
  namespace :admin do
    devise_scope :admin_user do
      get '/stats/:scope' => "stats#stats", as: :admin_stats
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  post '/signup' => 'splash#signup', as: :splash_signup
  get '/spash' => 'splash#index'
  get '/setup' => 'setup#index'

end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_filter :authenticate

  def index
  end

  def signup
    if ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'].blank? or ENV['MAILCHIMP_API_KEY'].blank?

      @message = "The MAILCHIMP_API_KEY and MAILCHIMP_SPLASH_SIGNUP_LIST_ID environment variables need to be set for mailing list signup to work! If you don't want this feature, you can just remove the mailing list signup feature from app/views/splash/index.html.haml"

    else
      begin

        gb = Gibbon::API.new

        gb.lists.subscribe({
          :id => ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'],
          :email => {:email => params[:signup_email]},
          :double_optin => true
        })

        @message = 'Thanks for signing up!'

      rescue StandardError => e
        @error = true

        if e.message =~ /is already subscribed to list/
          @message = "You're already signed up to receive updates. Thanks for your enthusiasm!"
        else
          @message = "Oops! Looks like we ran into an error. How embarrassing. Please try again later!"
        end

      end
    end
  end


  private
  
    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

end

app/views/splash/_environment_checks.html.haml
%ul.list-group

  - if ENV['AWS_ACCESS_KEY_ID'].blank? or ENV['AWS_SECRET_ACCESS_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 AWS
      You haven't set up your AWS account in this environment! Set the <code>AWS_ACCESS_KEY_ID</code> and <code>AWS_SECRET_ACCESS_KEY</code> environment variables to configure AWS. You should have the client sign up and follow the instructions below.
  - else
    %li.list-group-item.list-group-item-success
      %h4 AWS
      Your AWS account is configured for this environment!



  - if ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Google Analytics
      You haven't set up a Google Analytics account in this environment! Set the <code>GOOGLE_ANALYTICS_SITE_ID</code> environment variables to configure Google Analytics. You should ask the client to <a href="http://google.com/analytics/" target="_blank">set up a Google Analytics account</a>.
  - else
    %li.list-group-item.list-group-item-success
      %h4 Google Analytics
      Your Google Analytics account is configured for this environment!



  - unless @tracker_gems.values.any?
    %li.list-group-item.list-group-item-danger
      %h4 Exception Tracking
      You haven't set up an exception tracker! May I recommend <a href="https://addons.heroku.com/honeybadger" target="_blank">Honeybadger</a>?
  - else
    %li.list-group-item.list-group-item-success
      %h4 Exception Tracking
      Found exception tracker gems(s):
      = @tracker_gems.select{|k,v| v}.keys.join(', ')



  - if ENV['MAILCHIMP_API_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Mailchimp
      <p>You haven't set up a Mailchimp account in this environment! Have the client create an account at <a href="http://mailchimp.com" target="_blank">mailchimp.com</a> and set the <code>MAILCHIMP_API_KEY</code> environment variables to configure Mailchimp.</p>
      <p>Once a Mailchimp account is configured, you'll need to create a list through the web interface and set the <code>MAILCHIMP_SPLASH_SIGNUP_LIST_ID</code> environment variable to the list id (ten-digit hex id visible in the List name &amp; defaults tab).</p>
  - else
    %li.list-group-item.list-group-item-success
      %h4 Mailchimp
      Your Mailchimp account is configured for this environment!

app/views/splash/index.html.haml
%section.masthead.jumbotron
  .container
    .row#top
      .col-md-8.col-md-offset-2
        .panel.panel-default
          .panel-body
            .row
              .col-md-4.text-center.brand
                %h1
                  %span.glyphicon.glyphicon-cloud
                  %br
                  App
              .signup.col-md-7.col-md-offset-0.col-lg-7.col-lg-offset-0.col-sm-offset-2.col-sm-8
                %p.lead Get ready. We'll make your life easier and more&nbsp;meaningful.
                = form_tag splash_signup_path, role: :form, :class=>'form-horizontal', :remote=>true do
                  .form-group#signup
                    .col-sm-12
                      .input-group
                        = text_field_tag :signup_email, '',  :class=>'form-control', :placeholder=>'Enter your email to know when we launch!'
                        %span.input-group-btn
                          = submit_tag 'Sign up', :class=>'btn btn-primary'
                      %small#signup-message

.container.marketing
  .row#what
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details »
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details »
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details »

  / START THE FEATURETTES
  %hr.featurette-divider
    .row.featurette#feature1
      .col-md-7
        %h2.featurette-heading
          First featurette heading.
          %span.text-muted It'll blow your mind.
        %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
      .col-md-5
        %img.featurette-image.img-responsive{:alt => "500x500", "data-src" => "holder.js/500x500/auto", :src => "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjI1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjMxcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NTAweDUwMDwvdGV4dD48L3N2Zz4="}
    %hr.featurette-divider
      .row.featurette#feature2
        .col-md-5
          %img.featurette-image.img-responsive{:alt => "500x500", "data-src" => "holder.js/500x500/auto", :src => "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjI1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjMxcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NTAweDUwMDwvdGV4dD48L3N2Zz4="}
        .col-md-7
          %h2.featurette-heading
            Oh yeah, it's that good.
            %span.text-muted See for yourself.
          %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
      %hr.featurette-divider
        .row.featurette#feature3
          .col-md-7
            %h2.featurette-heading
              And lastly, this one.
              %span.text-muted Checkmate.
            %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
          .col-md-5
            %img.featurette-image.img-responsive{:alt => "500x500", "data-src" => "holder.js/500x500/auto", :src => "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIj48cmVjdCB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjI1MCIgeT0iMjUwIiBzdHlsZT0iZmlsbDojYWFhO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjMxcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NTAweDUwMDwvdGV4dD48L3N2Zz4="}
        %hr.featurette-divider
          / /END THE FEATURETTES
          / FOOTER
          %footer
            %p.pull-right
              %a{:href => "#"} Back to top
            %p
              © 2014 Company, Inc. ·
              %a{:href => "#"} Privacy
              ·
              %a{:href => "#"} Terms

app/views/splash/signup.js.erb
<% if @error %>
  $('#signup').addClass('has-error');
<% else %>
  $('#signup').removeClass('has-error');
  $('#signup_email').val('');
<% end %>

$('#signup-message').text("<%= j @message.html_safe %>").hide().slideDown('fast');